/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/kY8jLx7uO7O
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

import { Avatar, AvatarFallback, AvatarImage } from "@radix-ui/react-avatar";

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/


export function Chatbot() {
  return (
    (<div
      className="flex flex-col h-[80vh] max-h-[800px] w-full mx-auto bg-background rounded-2xl shadow-lg overflow-hidden">
      <header
        className="bg-primary w-full text-primary-foreground py-4 px-6 flex items-center justify-between">
        <div className="flex items-center gap-3">
          <Avatar className="w-8 h-8">
            <AvatarImage src="/placeholder-user.jpg" alt="Chatbot Avatar" />
            <AvatarFallback>CB</AvatarFallback>
          </Avatar>
          <h2 className="text-lg font-medium">Chatbot</h2>
        </div>
      </header>
      <div className="flex-1 overflow-y-auto p-6 space-y-4">
        <div className="flex items-start gap-4">
          <Avatar className="w-8 h-8">
            <AvatarImage src="/placeholder-user.jpg" alt="User Avatar" />
            <AvatarFallback>U</AvatarFallback>
          </Avatar>
          <div className="bg-muted rounded-2xl p-4 max-w-[70%]">
            <p>Hello, how can I assist you today?</p>
          </div>
        </div>
        <div className="flex items-start gap-4 justify-end">
          <div
            className="bg-primary text-primary-foreground rounded-2xl p-4 max-w-[70%]">
            <p>I'm looking for information on the latest trends in web development.</p>
          </div>
          <Avatar className="w-8 h-8">
            <AvatarImage src="/placeholder-user.jpg" alt="Chatbot Avatar" />
            <AvatarFallback>CB</AvatarFallback>
          </Avatar>
        </div>
        <div className="flex items-start gap-4">
          <Avatar className="w-8 h-8">
            <AvatarImage src="/placeholder-user.jpg" alt="User Avatar" />
            <AvatarFallback>U</AvatarFallback>
          </Avatar>
          <div className="bg-muted rounded-2xl p-4 max-w-[70%]">
            <p>That's great, I'd love to learn more about the latest trends.</p>
          </div>
        </div>
        <div className="flex items-start gap-4 justify-end">
          <div
            className="bg-primary text-primary-foreground rounded-2xl p-4 max-w-[70%]">
            <p>
              Some of the latest trends in web development include the increased use of React, Vue.js, and other modern
              JavaScript frameworks, as well as the growing popularity of headless CMS and static site generators.
            </p>
          </div>
          <Avatar className="w-8 h-8">
            <AvatarImage src="/placeholder-user.jpg" alt="Chatbot Avatar" />
            <AvatarFallback>CB</AvatarFallback>
          </Avatar>
        </div>
      </div>
      <div className="p-4 flex items-center gap-2 bg-slate-900">
        <input
          placeholder="Type your message..."
          className="flex-1 resize-none rounded-md border border-input bg-white px-4 py-2 text-sm shadow-sm placeholder:text-muted-foreground focus:outline-none focus:ring-1 focus:ring-ring disabled:cursor-not-allowed disabled:opacity-50" />
        <button
          type="submit"
          className="bg-primary text-primary-foreground rounded-lg px-4 py-2 text-md font-medium shadow-sm hover:bg-yellow-600 focus:outline-none focus:ring-1 focus:ring-ring disabled:cursor-not-allowed disabled:opacity-50">
          Send
        </button>
      </div>
    </div>)
  );
}

function XIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>)
  );
}
